name: CI/CD Docker - Docker Hub + Compose

on:
  push:
    # branches:
    #   - main # chạy khi push commit main
    tags:
      - 'v*' # chạy khi push Git tag versioned
  workflow_dispatch: # trigger thủ công

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code (workflow cần, server không dùng)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (nếu cần build image)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Log in Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build & push Docker image versioned
      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.NAME_IMAGE }}:${{ github.ref_name || github.run_number }}

      # 5. Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/liemdev/social
            # Lấy tag image: Git tag nếu có, nếu không dùng run_number
            if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              export IMAGE_TAG=${GITHUB_REF#refs/tags/}
            else
              export IMAGE_TAG=${GITHUB_RUN_NUMBER}
            fi
            echo "Deploying image tag: $IMAGE_TAG"
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans
